name: Drew Young Photography
favicon: null
layout_spectrum: 0.75461
typography_spectrum: 0.59836
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Drew Young Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-70775198-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f0404'
    - '#c8c9c2'
    - '#3b3324'
    - '#8e8795'
    - '#e7eef7'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
