name: Drew Young Photography
favicon: null
layout_spectrum: 0.49832
typography_spectrum: 0.90201
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Drew Young Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-70775198-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#182033'
    - '#ffffff'
    - '#5d79a1'
    - '#9aa4ae'
    - '#c9cfdb'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
